### ISSUE TITLE
The mod does not work

### ISSUE THREAD

**Issue by Kekere56** [2Retr0/BedrockWaters#37] opened 2023-08-22 16:41 UTC
I don't change the color of water in all biomes and dimensions. I do not know what this error is related to. If necessary, here is my build on which I play.
[
![image](https://github.com/2Retr0/BedrockWaters/assets/142924203/780fd396-e667-4169-8892-a135d25d1286)
](url)
![image](https://github.com/2Retr0/BedrockWaters/assets/142924203/1607e752-17d0-44d4-b094-34211c675d5d)
![image](https://github.com/2Retr0/BedrockWaters/assets/142924203/863b65c7-8c0c-4e47-8f76-8559d11cb376)
![image](https://github.com/2Retr0/BedrockWaters/assets/142924203/cbabe43a-7e2c-4363-bc9e-53f7470b35c0)
![image](https://github.com/2Retr0/BedrockWaters/assets/142924203/6d422a45-759d-4281-9e8c-058a72a6ad08)
![image](https://github.com/2Retr0/BedrockWaters/assets/142924203/449a2028-d98c-4752-9f34-977a70294c65)

**Comment by 2Retr0** [comment] 2024-01-15 00:12
Caused by an incompatibility with Sodium version 0.5.x. This has been fixed in version 1.8.0!

**Closed as completed by 2Retr0** 2024-01-15 00:12 UTC
