### ISSUE TITLE
bunch of errors

### ISSUE THREAD

**Issue by Aces-and-Jacks** [2Retr0/BedrockWaters#27] opened 2022-12-24 22:45 UTC
https://mclo.gs/FggHtJS

1.7.3
1.19.2
macOS 

on a server it repeats a lot and causes lag and crash

**Comment by Aces-and-Jacks** [comment] 2023-01-01 21:03
basically mod breaks

**Comment by 2Retr0** [comment] 2024-01-15 00:34
Duplicate of: #30

**Closed as completed by 2Retr0** 2024-01-15 00:34 UTC
